name: Security Analysis - OWASP Dependency Check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MyProject"
          path: "."
          format: "JSON"
          out: "reports/dependency-check"

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: reports/dependency-check/dependency-check-report.json

name: Security Analysis - Semgrep (SAST)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"               # analyse automatique selon le langage
          output: "reports/semgrep-report.sarif"
          output-format: "sarif"

      - name: Upload SAST report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: reports/semgrep-report.sarif
